### ISSUE TITLE
Posts/Blog - Blank Page!

### ISSUE THREAD

**Issue by ChrisVitale** [madoublet/respond#296]
Running into an issue where the Blog page won't load any posts. Everything is published properly, but none of the content gets loaded.

Unsure if it's unrelated, but I'm seeing quite a few issues in the console.
`Uncaught ReferenceError: respond is not defined - respond-build.html:1`
`Uncaught SyntaxError: Unexpected string - respond.site.js:246`

**Comment by madoublet** [comment]
Most of the components rely on respond.site.js, so that explains why you probably aren't seeing any components loading.  A few questions...
- Have you modified the theme at all?  The respond.site.js file needs to be loaded before the respond-build.html import.  This also needs to be in the head of the document.
- Are you seeing the respond.site.js file in your site folder (e.g. respond/app/sites/my-site/js/respond.site.js)?

If you could provide me a link to the site, I can help figure out what is going on.

**Comment by ChrisVitale** [comment]
No modification to the theme, and the respond.site.js file is in the proper folder. 

That being said, woke up this morning to take another crack at it, and was unable to reproduce. Works fine now. */shrug*

**Comment by madoublet** [comment]
I think we are good on this.  Let me know if you experience it again.
