### ISSUE TITLE
No possibility to change language

### ISSUE THREAD

**Issue by Tangoso** [madoublet/respond#336]
Hello,
I have a problem with version 5.1 (master or dev, clean install) : 
When i want switch language of the site, i have an infinite loading icon and no other language in the liste.

I had this problem one time, and in don't know how I have corrected it. 
In master : 
![infinite loading](https://cloud.githubusercontent.com/assets/13778016/9270907/b5d89a2e-4275-11e5-9281-e861150fdf1a.PNG)
In dev : 
![infinite loading2](https://cloud.githubusercontent.com/assets/13778016/9270906/b5d6a4b2-4275-11e5-96d3-ca4f2f968f37.PNG)

If you had any suggestion...
Thank you !

**Comment by madoublet** [comment]
Are you seeing any errors in the console?

**Comment by Tangoso** [comment]
Yes : 
![error](https://cloud.githubusercontent.com/assets/13778016/9275624/a96e3e50-429e-11e5-97d4-cf8535fdd527.PNG)

**Comment by madoublet** [comment]
I am seeing this error too.  I will look into it.

**Comment by joebordes** [comment]
Let me look into it.  I am finishing something and will try to fix this. 
It is probably related to fr translation i accepted a few days ago.

**Comment by joebordes** [comment]
@Tangoso, please try the patch I just uploaded when you can and let us know how it goes.

@madoublet, I don't think the solution I provide here is the correct one. It seems related to JWT authentication after upgrading to their latest version (I also had to add the "use" we spoke about in #325). All I did was avoid a warning message because now there is no value for HTTP_X_AUTH but this may be avoiding the validation completely. Please have a look when you can because I have no idea how JWT works.

**Comment by madoublet** [comment]
Yeah, the solution is fine.  That specific API call can be accessed via the app (authenticated using the token) or via a site (no auth needed).
