### ISSUE TITLE
First login doesn't work

### ISSUE THREAD

**Issue by DaSchTour** [madoublet/respond#346]
I did everything like described in the installation documentation. Creating a new side also went through without error. Now I wanted to login and I only get this cryptic error in my console and nothing happens.

[Error] Error: undefined is not an object (evaluating 'data.user.CanEdit')
http://example.com/js/respond.controllers.js:1932:18
http://example.com/js/respond.libs.min.js:86:27
http://example.com/js/respond.libs.min.js:119:303
$eval@http://example.com/js/respond.libs.min.js:134:83
$digest@http://example.com/js/respond.libs.min.js:131:111
$apply@http://example.com/js/respond.libs.min.js:134:368
l@http://example.com/js/respond.libs.min.js:86:333
M@http://example.com/js/respond.libs.min.js:90:656
onload@http://example.com/js/respond.libs.min.js:91:395
	(anonyme Funktion) (respond.libs.min.js, line 107)
	(anonyme Funktion) (respond.libs.min.js, line 80)
	(anonyme Funktion) (respond.libs.min.js, line 119)
	$eval (respond.libs.min.js, line 134)
	$digest (respond.libs.min.js, line 131)
	$apply (respond.libs.min.js, line 134)
	l (respond.libs.min.js, line 86)
	M (respond.libs.min.js, line 90)
	onload (respond.libs.min.js, line 91)

I already tried to work with Respond some months ago and I abandoned the project because it was very buggy. Now searched for a CMS with Angular and Bootstrap and again Respond showed up. I though, oh great they developed a lot and work with modern technology. But again after 5 minutes I run into some strange error I have no idea how to fix. It's sad to see that respond CMS still can't compete with CMS like Wordpress in terms of stability and easy-to-use.

**Comment by madoublet** [comment]
Hmm.  I haven't seen that error before. Can you email me (matt@matthewsmith.com) a link to your build so I can check it out?

**Comment by n3ssi3** [comment]
I'm having the same error.

**1.**
I got the error in MySQL, that 'WelcomeEmail' can not have a default value.
Since the value is empty anyways, I just created it without the default value (not sure if this already can cause an issue)

**2.**
When I go to /#/create I get the warning:
```
[Site::GetDomains] PDO Error: SQLSTATE[HY000] [2002] No such file or directory
```
and an angularjs error 
```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.4.0/ngRepeat/dupes?p0=theme%20in%20themes&p1=string%3A%3A&p2=%3A
```
  - I think this causes the problem
  - I tried to fill out the form and create my site.
  - I get to the next page saying "please login in at /#/login/mysite"

**3.**
 I go to /#/login/mysite and get the error 
```
TypeError: Cannot read property 'CanEdit' of undefined
```
  - If I check the database, there was never a Site or a User created. My database is completely empty

I hope this helps :)

**Comment by n3ssi3** [comment]
@DaSchTour I was debugging some more. My problem was, that PHP couldn't connect to MySQL.
I fixed it by changing
```
define('DB_HOST', 'localhost');
```
to
```
define('DB_HOST', '127.0.0.1');
```
After that all the other errors also disappear.

I hope that fixes your problem too

**Comment by madoublet** [comment]
The test page (e.g. https://demo.respondcms.com/test/) should have caught this.  Did you not get an error there?

**Comment by DaSchTour** [comment]
Everything was fine till I tried to login

**Comment by bendobos** [comment]
I am having the same issues. First, I had to take out the default values for WelcomeEmail and some other fields. Shouldn't be a big deal since those are empty anyways. 
After creating a site, when I try to login, I get this error: `Error: undefined is not an object (evaluating 'data.user.CanEdit')`

Interestingly, when I open up the /test page, I get ` Connection to API failed`, however if I open up `/app/api/site/test`, I get `API works!`...

@madoublet I have also e-mailed you a link to my site with login credentials.

**Comment by caiohamamura** [comment]
Here I got this error when trying to login.

Error: data.user is undefined
$scope.login/<@http://localhost:44313//js/respond.controllers.js:1932:1
k/g.success/<@http://localhost:44313//js/respond.libs.min.js:86:26
f/<@http://localhost:44313//js/respond.libs.min.js:119:302
hf/this.$get</m.prototype.$eval@http://localhost:44313//js/respond.libs.min.js:134:79
hf/this.$get</m.prototype.$digest@http://localhost:44313//js/respond.libs.min.js:131:98
hf/this.$get</m.prototype.$apply@http://localhost:44313//js/respond.libs.min.js:134:359
l@http://localhost:44313//js/respond.libs.min.js:86:325
M@http://localhost:44313//js/respond.libs.min.js:90:370
Rf/</x.onload@http://localhost:44313//js/respond.libs.min.js:91:394
