### ISSUE TITLE
site.ImagesUrl not replaced on translation

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#384]
Hello @madoublet 
there is an issue with translations and site.ImagesUrl params.

TEST CASE:
create new website
load an image element from editor and upload a new image
activate the language menu btn
reload the website
switch to another language 
you will see the image won't be loaded and inside the url there is the site.ImagesUrl param not replaced.

I've created a demo website to let you try:
Go to: https://demo.respondcms.com/sites/imagetest/
Click on translate button and select FR.
Some method will replace the original URL with `{{site.ImagesUrl}}files/mountains.png`

Please, could you confirm ?
Thank you

**Comment by AndryBray** [comment]
IMO the problem is inside the translation method which is going to replace the image-x string.
Looking at the translation json file there is the same value "{{site.ImagesUrl}}files/mountains.png"

**Comment by AndryBray** [comment]
Confirmed. Setting FR as default language the image src will work but EN language is broken.

**Comment by AndryBray** [comment]
Here is the fix:

File: `/site/js/respond.site.js` Function `i18n`
```
line #117
// return i18n.t(text);	 #here we need to replace site.ImagesUrl with current domain
var t = i18n.t(text);
return this.replaceAll(t, '{{site.ImagesUrl}}', respond.site.settings.Domain + '/');
```

Enjoy!

**Comment by axis80** [comment]
I checked your test case and confirmed the issue.

I would be glad to apply this fix, but first I want to make sure I fully understand the issue.  I don't use the language translation feature, so I have never looked at how it works.

I see why the default language works.  It's because the {{site.ImagesUrl}} is replaced at the time the site is published into .html files.

What I don't understand is what causes the {{site.ImagesUrl}} to reappear when the language is switched.  Does the site retrieve and re-render the layout template when a new language is selected?

I appreciate any explanations you can provide - as well as your patience - while I work to better understand what is happening here.

**Comment by AndryBray** [comment]
This happens because the {{site.ImagesUrl}} is stored inside the translation json file (translation does not build other html files, this is just stored inside a json file and deployed).

So at the time of translation this must be replaced with the site base url.
