### ISSUE TITLE
Parallax needs update for IE10+

### ISSUE THREAD

**Issue by AndryBray** [madoublet/respond#388]
I see there is an issue scrolling images with parallax effect.
Upgrading to latest of http://pixelcog.github.io/parallax.js/ (at the time of writing it's 1.4.2) it solves the problem.

Maybe add this to next release.
https://raw.githubusercontent.com/pixelcog/parallax.js/master/parallax.min.js

**Comment by axis80** [comment]
Sounds good.  I want to upgrade all JS libraries to their current stable versions anyway.

@madoublet , it looks like alll the JS libraries in /site/js/libs.min.js are concatenated together manually using a text editor, rather than any sort of minification script.  Is that the case?  If so, I'll either update them all in the same way, or set them up to be minified by gulp along with the other scripts used by the editor.

**Comment by madoublet** [comment]
Closing issues not related to R6.
