### ISSUE TITLE
Cannot upload image in docker container

### ISSUE THREAD

**Issue by lazydino** [madoublet/respond#429]
I am testing with the docker container. I am not able to upload a png image of 40k. Chrome network debug says  
<br />
<b>Fatal error</b>:  Call to undefined function imagecreatefrompng() in <b>/app/api/libs/Image.php</b> on line <b>82</b><br />

Something to do with gd library? http://stackoverflow.com/questions/30856865/php-fatal-error-call-to-undefined-function-imagecreatefrompng

**Comment by axis80** [comment]
Correct.  You are getting this error because you don't have the necessary PHP module installed.  

For RedHat/Centos try "yum install php-gd" or for Debian/Ubuntu try "sudo apt-get install php-gd".

If those commands don't work, it's probably best to consult with your server provider for direction on enabling the GD library.

**Comment by lazydino** [comment]
So the dockerfile in this repos does not build a GD enabled image? Will patch it up with php-gd and try again.

**Comment by madoublet** [comment]
Closing issues not related to R6.
