### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by madoublet** [madoublet/respond#435]
Support layouts in the app.  Will check to see if this is possible within the editor, if not this will be definitely be an option at page creation.

**Comment by scubamiller** [comment]
I think it is very important, almost critical, for the end user to be able to have that functionality. That is one of my favorite features of respond 5. If an end  user is initially creating a page or is just going back to change the looks of an existing page and they need to modify the layout to include a new block with multiple columns it would be very time consuming to have to recreate the whole page. Many people try one look, ask for opinions and then modify the layout until they are happy with it. This feature makes that whole process much easier than other CMS options.  I really hope this can be part of RespondCMS 6.

**Comment by madoublet** [comment]
This is now in Respond 6 Beta 3.

**Comment by scubamiller** [comment]
Thank you.

 

I just got back in and upgraded to Respond 6 Beta 3 

 

Now when I hover of a section I see a Plus and a move up,  Move Down and a Trash can. They all work except for the Plus.

 

When I click the plus to add a section a window pops up and gives me the choice of   1 column 100% but no other choices.

 

Thanks

Tim Miller

**Comment by madoublet** [comment]
The behavior of this modal is setup in the "grid" setting of the settings.json file.  For an existing site, you will need to update this to support multiple columns.  The file will be located in /resources/sites/site-name/.  See an example here:

https://github.com/madoublet/respond/blob/master/public/themes/bootstrap/private/settings.json

**Comment by madoublet** [comment]
There are two settings that drive the sorting of the grid.  The "blocks" is the selector used by the system to select the blocks.  The "grid" setting is used to define how the new blocks are created.

**Comment by scubamiller** [comment]
Matthew;

 

That worked! 

 

We also are adding plugins so we can include content just by having the user drag and drop from your top menu.

We are adding a files called gunrodeo.html to the plugins folder for EACH template and also modifying the plugins.js for each site.

1.       Is there a better way to do this globally?

2.       How can we do it so it does not get over written each time we do an upgrade?

 

When  you helped me install all of the themes you created a folder called respond-themes.

1.       Can you also tell me the location of the config file that you changed to use that folder instead of the default folder?

2.       When we do an upgrade via the zip method, I assume that this config file is overwritten and pull the themes from the default location.

 

 

Also is there any facility to include php code and have it execute? Simular to the Insert HTML plugin.

 

 

Thank you!

 

Tim Miller

Gun.Rodeo
