### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by JonatanPotrikus** [madoublet/respond#533]
Hello, the demo page of RespondCms, is not working.

![image](https://user-images.githubusercontent.com/28599893/29666606-5fbfa18c-88af-11e7-8263-54326c52a797.png)

![image](https://user-images.githubusercontent.com/28599893/29666675-b630e7b0-88af-11e7-98e7-aaa0b663a3a5.png)

Seems to be missing solving a captcha.

https://demo.respondcms.com/create

**Comment by madoublet** [comment]
Thank you.  I removed the reCAPTCHA for now.  I think there is an issue with how the reCAPTCHA library is loaded using the CLI, because I do sometimes see the reCAPTCHA.  I logged an issue to track this problem:

https://github.com/madoublet/respond/issues/534

I am going to close this issue and use 534 to track the problem.
