### ISSUE TITLE
reCAPTCHA not loading

### ISSUE THREAD

**Issue by madoublet** [madoublet/respond#534]
The reCAPTCHA is not loading consistently since the launch of the CLI.

**Comment by axis80** [comment]
In my experience when something doesn't load consistently it's caused by a race condition.  Like, something is trying to insert a DOM node within another DOM node that may or may not have been created yet.  Or, something is attempting to call a Javascript function that hasn't been registered yet. Just my two cents.

**Comment by madoublet** [comment]
This is fixed now.  I changed reCAPTCHA to render "explicit" after the script loaded.  See: https://developers.google.com/recaptcha/docs/display#render_param

**Comment by madoublet** [comment]
Fixed in 6.4.1
