### ISSUE TITLE
Investigate alternatives to Lumen

### ISSUE THREAD

**Issue by madoublet** [madoublet/respond#571]
I had an open task to move Lumen to the latest version.  However, the latest version requires PHP7.  This could potentially impact adoption.  I definitely want to make Respond work with PHP7, but I am not sure this is the right time to limit it to PHP7. 

Given that Respond only uses a small percentage of Lumen's functionality, I want to investigate moving to another framework or removing PHP frameworks altogether from Respond.  If I put in the time to do this, I would also want to remove the mod_rewrite requirement as this has been a huge point of confusion and frustration around installing Respond.

Goals:
- PHP 5.6+
- Clean, well-structured code
- Remove requirement for mod_rewrite

cc: @axis80 @AKAsebu

**Comment by madoublet** [comment]
As an aside, I am doing a POC around removing a routing framework entirely from Respond.  I think this might be the most viable route as every routing framework that I have investigated (Slim, Lumen, Laravel, etc) seems to require mod_rewrite.  This requirement completely makes sense, but it is also the #1 complaint for Respond installation issues.

**Comment by madoublet** [comment]
For me, the big change around removing a framework is that you do not get friendly URLs.  For example, /api/user/login would become /api/user/login.php.  I think I can have this be a configuration option in the Angular app so that the code changes would be minimal.

**Comment by axis80** [comment]
From my perspective, it seems reasonable to require PHP7 at the current time.  I manage a number of Ubuntu and CentOS machines, and those OSes have shipped with PHP7 as the installed default version for about the last three major versions.  Any Linux OS that is old enough to be running PHP5 is well past EOL.  I'm not sure what PHP7 support is like in the shared hosting world, and I'm not at all familiar with MacOS.  I would be surprised if those environments have less robust PHP7 support then the virtual servers I work with, but I suppose it's possible.

It seems to me that moving to an entirely different PHP framework would require a significant amount of work, and could potentially introduce some instability that would take a few patch releases to shake out.  I also don't see any benefit to moving away from Lumen, as IMHO it is one of the very best PHP microframeworks out there.  If PHP5 support is that important why not just wait until the next major or minor Respond release to bump the Lumen version, and save yourself a lot of work?

I don't object as much to the idea of entirely removing the PHP framework.  My biggest concern with that is not the pretty URLs (which I don't think matter for the Respond SPA) but with losing access to Lumen's array of HTTP middleware options.  There are a lot of filters that can help to sanitize request data, thwart crawler bots, authenticate users against various SSO providers, etc.  Not sure how many of those are currently used by Respond, but they could potentially be important for security.

As for the pretty URLs, like I said I don't think they're a concern.  If the change would affect only the REST API endpoints, then they are not even seen by the public so it doesn't matter how pretty the URLs are.  If it would also affect the URLs in the SPA, I still think the change would be fine to make.  We're not concerned about SEO in the editor, and the addition of a .php extension doesn't significantly obfuscate the meaning of the URLs.  Having pretty app URLs is a minor aesthetic consideration, and it sounds like the tradeoff in installation complexity is not worth it.

**Comment by madoublet** [comment]
You bring up a good point.  I think this would be a good opportunity to take a look at input processing in Respond.  Currently, Respond relies on what comes out-of-the-box with Lumen.  But, I think I would need to add an added sanitize check (e.g.https://stackoverflow.com/questions/37533162/sanitize-json-with-php)

**Comment by madoublet** [comment]
FYI, I did verify that adding a .php extension can be done from a configuration setting.

**Comment by madoublet** [comment]
... in Angular.  So, the front-end would be untouched.  Also, I can reuse all the code in the /Respond lib folder (https://github.com/madoublet/respond/tree/master/app/Respond).  This is the core of the application.  So, really the only change would be at the controllers.

**Comment by axis80** [comment]
If the installation problems are just a matter of the module not being installed, there is probably a simple way to test for its presence and let people know to install it.  For example, you might include an IfModule directive in .htaccess that tests for the absence of that module and redirects to a friendly error message if it isn't present.  I just checked, and it is possible to use the syntax `<IfModule !mod_rewrite.c>` within .htaccess to test for the absence of mod_rewrite.  Just spitballing ideas for solutions to the installation problems.  

Also, I don't think you need to get rid of Lumen to remove the mod_rewrite requirement.  I'm pretty sure it's possible to use it with URLs like /index.php/about instead of /about when mod_rewrite isn't installed.  You could make it work that way out of the box, and allow admins to enable friendly URLs in .env, with a note that mod_rewrite is required.  I think that's what you already had in mind - I'm just clarifying that it can probably be done with Lumen intact.

It should actually be possible for Respond to autodetect whether mod_rewrite is available and pass that information to Angular.  We could use `<IfModule mod_rewrite.c>` in the .htaccess to add a custom "rewrite=true" HTTP header to the API response, that could be read by Angular.  I think I'd rather just make it an .env option though.

I'm getting a little too random now.  I think any of the approaches you've mentioned are workable, and I'll support whatever decision you make.

**Comment by madoublet** [comment]
This is a quick POC of Respond without a backend library.  

The router is replaced by folders in:
https://github.com/madoublet/respond-beta/tree/master/public/api

The core of the Respond code stays intact with minor find-and-replace modifications:
https://github.com/madoublet/respond-beta/tree/master/app/Respond

Note how simplified the project is now:
https://github.com/madoublet/respond-beta

**Comment by axis80** [comment]
Color me impressed.  I haven't run it but I looked over all the code and that's pretty cool.  That index.php should be fine as long as the API back end doesn't grow in complexity.  I'll bet it runs faster without the routing and framework overhead.

If you'll let me know when you have it to a beta state I will be glad to do some functional testing and see if I can break it.

**Comment by madoublet** [comment]
Cool!  Thank you!  That would be great to have someone else test it.  Right now, there is not much going on.  But, it does let you login and pull a list of pages from the site.  Honestly, I am not sure it is going to get much more complicated.  I was probably using 5% of the utility of Lumen.

**Comment by AKAsebu** [comment]
From my point of view removing the PHP framework is a dangerous choice for the project. 

We need to keep the framework in order to guarantees that Respond complies with industry rules, is well structured, maintainable and scalable. It also saves developers time (e.g. for IT dependencies), by reusing generic modules, so they can focus on specific business features.

If you want to move to a new PHP framework maybe you can take a look into [Symfony](https://github.com/symfony/symfony) CMS like Drupal, eZ Publish, Magento, PrestaShop have already make the switch for Symfony.

**Comment by madoublet** [comment]
This is what Respond actually uses in Lumen:
- Routing
- HTTP response/request wrapper
- HTTP middleware
- Location of the root of the app

In my opinion, these are the pros for sticking with Lumen:
- Simplified routing / HTTP requests
- Familiarity for new code contributors (can read framework docs)

And, here are the cons for Lumen:
- Can't run composer on low memory VPS
- Installation requires mod_rewrite (or similar) for routing
- Upgrade path requires PHP7+
- Lots of code/dependencies that go unused
- Big ZIP download or long composer install process

For me the cons are just really bad right now.  I don't want to require PHP7, and the mod_rewrite issue is a HUGE barrier for new Respond installations.

**Comment by madoublet** [comment]
I am going to pause this for now but keep the issue open for discussion.

**Comment by madoublet** [comment]
Closing this issue.  Going to stick with Lumen.  Plan is to update it to 5.4 and then move to 5.5 (requires PHP7) later in the year to give everyone time to migrate their servers.
