### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by cweiske** [madoublet/respond#599]
There are no installation instructions in the README. Here is what I had to do:

1. fix node_modules -> https://github.com/madoublet/respond/issues/598
2. Create directories and set permissions:
```
mkdir resources/sites public/sites
chgrp -R www-data resources/sites public/sites storage
chmod -R g+w resources/sites public/sites storage
```
3. Copy .env.example to .env
4. Install dependencies
```
composer install
npm install
gulp resources
gulp themes
gulp combine
```

Not sure if there is more to do.

But with that I could actually create a new site (password is in .env, "iloverespond")

**Comment by axis80** [comment]
Thanks for your report.  Based on it, I've committed two changes that will hopefully improve the installation experience:

1. The installation instructions are on the respondcms.com web site.  Rather than repeat them in the readme, I simply linked to them.  I just stepped through the "installing from github" instructions and they worked.  I have not gone through the "installing from ZIP" instructions.  

2. I created a default gulp task, so now you can just type "gulp" instead of having to run those three tasks separately.

There is probably more that can be done.  If you come across any other documentation that needs to be updated, please don't hesitate to open an issue and I'll do my best to get it fixed.
