### ISSUE TITLE
Remove layout from page

### ISSUE THREAD

**Issue by cweiske** [madoublet/respond#605]
How can I remove a layout that i added to a page, e.g. the 3 column layout?
I can't find an obvious way to do this.

Also, the layout always gets added at top of the page, not at the place of the cursor, which makes it hard to combine multiple layouts in one page.

**Comment by axis80** [comment]
To remove a layout, you simply click to select any element within that layout, then click the "remove" button in the left column.  (Make sure to click the button under the "layout" heading rather than the "element" heading.)

I agree this could be made more obvious, perhaps by outlining the selected layout with a CSS border.

I don't know whether it's practical to add new layouts at the location of the cursor, because there really isn't a cursor per se, but it might make more sense to add them at the bottom of the page.

**Comment by cweiske** [comment]
Thanks!
